### ISSUE TITLE
CertificateDsc: Converting to new CI pipeline

### ISSUE THREAD

**Issue by johlju** [dsccommunity/CertificateDsc#219] opened 2020-03-06 11:52 UTC
Work need to be done to convert this repository to use the new CI pipeline.

https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery/

**Comment by PlagueHO** [comment] 2020-03-28 00:03
Duplicate of #215. Working on it now.

**Closed** 2020-03-31 19:09 UTC
Labels: blocking release, in progress
