### ISSUE TITLE
PfxImport: "No keys found for certificate!" when using Windows Server 2019

### ISSUE THREAD

**Issue by regularroutine** [dsccommunity/CertificateDsc#213] opened 2019-11-26 12:27 UTC
####  Details of the scenario you tried and the problem that is occurring
I am trying to import a certificate in Windows Server 2019 and later manage the keys. When I use the simple configuration below, it imports the certificate fine but when I go to "certlm" and try to "manage private keys" I get the error message: "No keys found for certificate!".
The same configuration works fine on Windows Server 2016.

#### Verbose logs showing the problem
No logs available to share
#### Suggested solution to the issue
Unsure what is causing the problem
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
Configuration Sample_Pfx
{
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullorEmpty()]
        [System.Management.Automation.PSCredential]
        $Credential
    )
    Import-DscResource -ModuleName PSDesiredStateConfiguration
    Import-DscResource -Module CertificateDsc
    Node $AllNodes.NodeName
    {
        PfxImport RKAppsTestLocalCertImport
        {
            Thumbprint = "XXXX"
            Path       = "\\path\cert.pfx"
            Location   = 'LocalMachine'
            Store      = 'MY'
            Credential = $Credential
        }
    }
}
$cd = @{
    AllNodes = @(
        @{
            NodeName = 'servername'
            PSDscAllowPlainTextPassword = $true
        }
    )
}
$cred = Get-Credential -UserName "cert" -Message "Password please"
Sample_Pfx -Credential $cred -ConfigurationData $cd

Start-DscConfiguration Sample_Pfx  
```

#### The operating system the target node is running
**Not working:**
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

**Working:**
OsName               : Microsoft Windows Server 2016 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.3269.amd64fre.rs1_release.190929-1234
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
#### Version and build of PowerShell the target node is running
**Not working:**
Name                           Value                                                            
----                           -----                                                            
PSVersion                      5.1.17763.771                                                    
PSEdition                      Desktop                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                          
BuildVersion                   10.0.17763.771                                                   
CLRVersion                     4.0.30319.42000                                                  
WSManStackVersion              3.0                                                              
PSRemotingProtocolVersion      2.3                                                              
SerializationVersion           1.1.0.1       

**Working:**
Name                           Value                                                            
----                           -----                                                            
PSVersion                      5.1.14393.3053                                                   
PSEdition                      Desktop                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                          
BuildVersion                   10.0.14393.3053                                                  
CLRVersion                     4.0.30319.42000                                                  
WSManStackVersion              3.0                                                              
PSRemotingProtocolVersion      2.3                                                              
SerializationVersion           1.1.0.1  

#### Version of the DSC module that was used ('dev' if using current dev branch)
4.5.0.0

**Comment by parnasoft** [comment] 2020-03-17 05:41
Any updates on this? 
I have the same problem Windows Server 2019.  The same configuration works on Windows Server 2016.

PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

as well as 

PSVersion                      5.1.17763.1007
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1007
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by PlagueHO** [comment] 2020-03-17 05:46
Hi @regularroutine - sorry for not getting back to you sooner on this.

This resource just uses the `Import-PfxCertificate` cmdlet in Windows to import the PFX. Can you confirm what happens if you use the `Import-PfxCertificate` cmdlet on Windows Server 2019 to import the same certificate? Do you see the same behaviour?

Also, can you do a `Get-ChildItem -Path cert:\LocalMachine\My\XXXX | fl *' and return the results after importing the PFX (where XXX is the thumbprint of your cert)?

**Comment by Altern1ty** [comment] 2020-03-17 21:06
We also have this problem. If I import via Import-PfxCertificate though it does grab the private key properly it seems like and I can set permissions on the private key where as I get the same error as above if I do it via Cert DSC. This same DSC code is used for our 2016 servers and works correctly.  Here is the output from the cert:


Imported via CertificateDsc

PSPath                   : Microsoft.PowerShell.Security\Certificate::LocalMachine\My\*******
PSParentPath             : Microsoft.PowerShell.Security\Certificate::LocalMachine\My
PSChildName              : ******
PSDrive                  : Cert
PSProvider               : Microsoft.PowerShell.Security\Certificate
PSIsContainer            : False
EnhancedKeyUsageList     : {Document Encryption (1.3.6.1.4.1.311.80.1)}
DnsNameList              : *******
SendAsTrustedIssuer      : False
EnrollmentPolicyEndPoint : Microsoft.CertificateServices.Commands.EnrollmentEndPointProperty
EnrollmentServerEndPoint : Microsoft.CertificateServices.Commands.EnrollmentEndPointProperty
PolicyId                 :
Archived                 : False
Extensions               : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid,
                           System.Security.Cryptography.Oid, System.Security.Cryptography.Oid}
FriendlyName             :
IssuerName               : System.Security.Cryptography.X509Certificates.X500DistinguishedName
NotAfter                 : *****
NotBefore                : *********
HasPrivateKey            : True
PrivateKey               :
PublicKey                : System.Security.Cryptography.X509Certificates.PublicKey
RawData                  : *********
SerialNumber             : *********
SubjectName              : System.Security.Cryptography.X509Certificates.X500DistinguishedName
SignatureAlgorithm       : System.Security.Cryptography.Oid
Thumbprint               : *********
Version                  : 3
Handle                   : *********
Issuer                   : *********
Subject                  : *********

Imported via Import-PfxCertificate

PSPath                   : Microsoft.PowerShell.Security\Certificate::LocalMachine\My\*********
PSParentPath             : Microsoft.PowerShell.Security\Certificate::LocalMachine\My
PSChildName              : *********
PSDrive                  : Cert
PSProvider               : Microsoft.PowerShell.Security\Certificate
PSIsContainer            : False
EnhancedKeyUsageList     : {Document Encryption (1.3.6.1.4.1.311.80.1)}
DnsNameList              : *********
SendAsTrustedIssuer      : False
EnrollmentPolicyEndPoint : Microsoft.CertificateServices.Commands.EnrollmentEndPointProperty
EnrollmentServerEndPoint : Microsoft.CertificateServices.Commands.EnrollmentEndPointProperty
PolicyId                 :
Archived                 : False
Extensions               : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid,
                           System.Security.Cryptography.Oid, System.Security.Cryptography.Oid}
FriendlyName             :
IssuerName               : System.Security.Cryptography.X509Certificates.X500DistinguishedName
NotAfter                 : *********
NotBefore                : *********
HasPrivateKey            : True
PrivateKey               : System.Security.Cryptography.RSACryptoServiceProvider
PublicKey                : System.Security.Cryptography.X509Certificates.PublicKey
RawData                  : *********
SerialNumber             : *********
SubjectName              : System.Security.Cryptography.X509Certificates.X500DistinguishedName
SignatureAlgorithm       : System.Security.Cryptography.Oid
Thumbprint               : *********
Version                  : 3
Handle                   : *********
Issuer                   : *********
Subject                  : *********


As you can see via CertificateDsc it shows that it has the private key as true, but the actual PrivateKey line is blank.

I know there are a variety of bugs around PFX certs in Windows and how it can falsely show as having imported the private key, but I haven't had issues with it via CertificateDsc before.

**Comment by PlagueHO** [comment] 2020-03-18 05:12
I wonder if this has to do with the fact that DSC runs under the context of Local System as this appears to be the only difference here?

Are you able to use the PsDscRunAsCredential to run the ImportPfx resource under a different context (e.g. not Local System)? https://docs.microsoft.com/en-us/powershell/scripting/dsc/configurations/runasuser?view=powershell-7

**Comment by Altern1ty** [comment] 2020-03-18 21:25
Good idea, unfortunately it did not help... ran it as both a local admin and as a domain admin account via PsDscRunAsCredential.

Also tested both on another freshly imaged 2016 box and they worked flawlessly, I was able to access the keys without issue.

Seems to only affect 2019.

**Comment by PlagueHO** [comment] 2020-03-19 04:58
Hi @Altern1ty , I'm really scratching my head here.

I'm trying to identify a difference in how the DSC resource imports the PFX and how you did it manually:
1. When you imported the PFX using `Import-PfxCertificate`, did you specify Exportable? 
2. It appears your DSC is not setting a FriendlyName - is that correct?

Otherwise, the code that imports the PFX in the DSC resource is just:
```powershell
            $importPfxCertificateParameters = @{
                Exportable        = $Exportable
                CertStoreLocation = $certificateStore
                FilePath          = $Path
                Verbose           = $VerbosePreference
            }

            if ($Credential)
            {
                $importPfxCertificateParameters['Password'] = $Credential.Password
            }

            # If the built in PKI cmdlet exists then use that, otherwise command in Common module.
            if (Test-CommandExists -Name 'Import-PfxCertificate')
            {
                Import-PfxCertificate @importPfxCertificateParameters
            }
            else
            {
                Import-PfxCertificateEx @importPfxCertificateParameters
            }
```

One thing that is possible but unlikely is that if the `Import-PfxCertificate` cmdlet can't be found on the system (is the case with older OS's) then it will use `Import-PfxCertificateEx`, which is based around some code I wrote. It _should_ work the same but perhaps for some reason it is falling back to this method?

**Comment by marcinbojko** [comment] 2020-08-03 15:22
Seems the Chef guys also had this issue
https://github.com/chef/chef/issues/8325

**Comment by Altern1ty** [comment] 2020-08-03 15:45
@PlagueHO wow I'm sorry I totally spaced on replying to this.

I ended up getting this to work when I used a domain user account as the run as user. Using a local account even with local admin did not work. Only a domain user that has local admin. Leaving it as the default SYSTEM did not work either.

I'd say this is a bug with the underlying import-pfxcertificate cmdlet or maybe one of the many bugs in Windows cert management.

Frankly I'd say you can close this as it should probably be an issue on the cmdlet or maybe with dotnet.

**Comment by marcinbojko** [comment] 2020-08-05 08:50
It seems i've found a reason.
On 2019 user SYSTEM doesn't have ANY rights to a folder:  "\Documents and Settings\All Users\Application Data\Microsoft\Crypto\RSA\MachineKeys", mostly system drive
On 2016 user SYSTEM does have full rights.
Is it by default? By design? An error? Hard to say, but I think adding one ACL before, should make us happy. Will test.

**Comment by zephrxx** [comment] 2020-08-07 01:06
@marcinbojko does your test work finally? I was blocked on this issue as well.

**Comment by PlagueHO** [comment] 2020-08-07 04:08
I can try to find out if this is by design. If it is by design then what we may need to try and grant rights on the folder before performing the import and then removing them again. But that isn't an ideal pattern (e.g. a failure in the resource could leave the folder in an insecure state). So understanding the reasoning behind this behavior in WS 2019 is important. Keen to hear the results of your testing @marcinbojko .

**Comment by marcinbojko** [comment] 2020-08-07 05:33
I didn't have time to do these tests, but a colleague of mine did workaround in a form of extra puppet/acl settings and he confirmed it worked.

```yaml
C_MachineKeys:
  inherit_parent_permissions: false
  purge: false
  permissions:
  - identity: Administrators
    rights:
    - full
  target: c:\Documents and Settings\All Users\Application Data\Microsoft\Crypto\RSA\MachineKeys
```

**Comment by PlagueHO** [comment] 2020-08-07 08:57
Maybe what we could do is add an option to the resource to allow this to be "forced" - that way it would be on a consumer to make the decision about whether to allow the temporary permission change on the folder. I'm still keen to understand the reasoning behind the change so will reach out internally.

**Comment by yiranrugu** [comment] 2020-08-07 18:31
@PlagueHO, I hit the same issue and tested with @marcinbojko's suggestion. I manually assigned SYSTEM full control access to folder "c:\Documents and Settings\All Users\Application Data\Microsoft\Crypto\RSA\MachineKeys", and run DSC again, it didn't work.
The other interesting thing is, before assigning SYSTEM access, I impersonate as SYSTEM and run import cert directly on vm as below, it worked.
_Import-PfxCertificate -FilePath $PfxPath -CertStoreLocation 'Cert:\LocalMachine\My\' -Exportable_

I'm confused about this issue now, if it is SYSTEM account access issue, why running on VM directly works.
@marcinbojko, Could you share where did you add the acl setting?

**Comment by marcinbojko** [comment] 2020-08-07 19:09
Hi @yiranrugu , the solution above adds administrators, not system. Haven't tested it myself.

**Comment by mib82** [comment] 2020-08-27 11:37
I have runned **pfxImport** resource with:
**PsDscRunAsCredential = $AdminDomainCredential**

and there is no error. Works fine!

**Comment by PlagueHO** [comment] 2020-08-28 00:20
Hi @mib82 - were you using Windows Server 2019 or an earlier version?

**Comment by mib82** [comment] 2020-08-28 08:43
Hi @PlagueHO 
Windows Server 2019 Datacenter

**Comment by PlagueHO** [comment] 2020-08-28 09:14
Hi @mib82 - thank you for confirming that. This is the same behavior on Windows Server 2016 - you generally need to import the certification using PsDscRunAsCredential set to admin. I didn't think to actually to check this at the time.

I think what I need to do is add this as an example.

**Closed** 2020-08-30 07:46 UTC
Labels: help wanted, needs investigation
